# Generated by Django 3.2.4 on 2021-06-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('runaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='runaways.runaway')),
            ],
        ),
    ]
